### ISSUE TITLE
Second example in README not working

### ISSUE THREAD

**Issue by wmayner** [altair-viz/altair-transform#30]
I'm trying out `altair-transform`, and when I run the second example, I still get the `MaxRowsError` even with `transform_chart(chart)`. Running `extract_data(chart)` doesn't work either; it gives me the input data unchanged.

Strangely, the first example works: `extract_data(line)` returns the aggregated dataframe.

altair v3.2.0
altair-transform v0.1.0

**Comment by jakevdp** [comment]
Sorry for the confusion: the second example only works with the master branch of the package. The package is under active development, so the released version is missing a lot of features.

**Comment by wmayner** [comment]
Gotcha. Thanks!
